Fix SyntaxManager test
First argument was `formatConverterFunction = None` and it was removed in this commit

https://github.com/andreikop/qutepart/commit/d54ad12d6b80df544a86a6c58b539b17cb21fb48

    TypeError: getSyntax() got multiple values for argument 'xmlFileName'