Fix: Use the UTF-8 encoding for all file I/O, instead of the default platform-dependent encoding.
Otherwise, I see errors like:

======================================================================
ERROR: test_parse_all_definitions (test_syntax.test_xml_definition_parsing.XmlPa
rsingTestCase)
Parse all definitions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\qutepart\tests\test_syntax\test_xml_d
efinition_parsing.py", line 25, in test_parse_all_definitions
    syntax = SyntaxManager().getSyntax(None, xmlFileName = xmlFileName)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\__init__.py"
, line 231, in getSyntax
    syntax = self._getSyntaxByXmlFileName(xmlFileName, formatConverterFunction)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\__init__.py"
, line 180, in _getSyntaxByXmlFileName
    qutepart.syntax.loader.loadSyntax(syntax, xmlFilePath, formatConverterFuncti
on)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 589, in loadSyntax
    _loadContexts(highlightingElement, syntax.parser, attributeToFormatMap, form
atConverterFunction)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 383, in _loadContexts
    _loadContext(context, xmlElement, attributeToFormatMap, formatConverterFunct
ion)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 421, in _loadContext
    rules = _loadChildRules(context, xmlElement, attributeToFormatMap, formatCon
verterFunction)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 176, in _loadChildRules
    rule = _ruleClassDict[ruleElement.tag](context, ruleElement, attributeToForm
atMap, formatConverterFunction)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 152, in _loadIncludeRules
    context = _getContext(contextName, parentContext.parser, formatConverterFunc
tion, parentContext.parser.defaultContext)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 110, in _getContext
    parser = parser.syntax.manager.getSyntax(formatConverterFunction, languageNa
me = syntaxName).parser
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\__init__.py"
, line 243, in getSyntax
    syntax = self._getSyntaxByLanguageName(languageName, formatConverterFunction
)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\__init__.py"
, line 188, in _getSyntaxByLanguageName
    return self._getSyntaxByXmlFileName(xmlFileName, formatConverterFunction)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\__init__.py"
, line 180, in _getSyntaxByXmlFileName
    qutepart.syntax.loader.loadSyntax(syntax, xmlFilePath, formatConverterFuncti
on)
  File "C:\Users\bjones\Documents\enki_all\qutepart\qutepart\syntax\loader.py",
line 541, in loadSyntax
    root = xml.etree.ElementTree.parse(definitionFile).getroot()
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\xml\etree\ElementTree.py", line 1187, in parse
    tree.parse(source, parser)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\xml\etree\ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
  File "C:\Users\bjones\Downloads\WinPython-64bit-3.4.3.7Qt5\python-3.4.3.amd64\
lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 10209: ch
aracter maps to <undefined>

----------------------------------------------------------------------